version: "3"

services:
  turtlebot3:
    container_name: turtlebot3
    image: turtlebot3:latest
    environment:
      - DISPLAY=${DISPLAY}
    tty: true
    volumes:
      - ./workspace:/home/turtle/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    